//using UnityEngine;


//namespace Core {
//    public class BasicCreepAttachment_Money : CreepAttatchment {
//        const float SCALE = 0.3f;

//        public override void ApplyModification(CreepStatModification results) {
//            results.AddMoneyScale(SCALE);
//        }

//        public override Sprite GetIcon() {
//            return CreepItemIconResourceCache.basicMoney;
//        }

//        public override string GetName() {
//            return "Money Module";
//        }

//        public override string GetDescription() {
//            return "Increases the money generated by the creeps by 30%";
//        }

//        public override CreepModificationLevel GetLevel() {
//            return CreepModificationLevel.L2;
//        }
//    }

//}
