using UnityEngine;


namespace Core {
    public class BasicCreepAttachment_Money : CreepAttatchment {
        const float SCALE = 0.3f;

        public override void ApplyModification(CreepDefinition baseDef, CreepDefinition result) {
            var baseState = baseDef.moneyReward;
            var additional = baseState * SCALE;
            result.moneyReward += additional;
        }

        public override Sprite GetIcon() {
            return IconResourceCache.creepAttachmentMoney;
        }

        public override string GetName() {
            return "Money Module";
        }

        public override string GetDescription() {
            return "Increases the money generated by the creeps by 30%";
        }
    }

}
